version: 0.2

phases:
  install:
    commands:
     - echo installing maven...
     - yum install -y maven 
  build:
    commands:
      - echo Build started on `date`
      - mvn install

artifacts:
  files:
    - '**/*.war'
    - 'appspec.yaml'
  discard-paths: yes